c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2015                     # [win]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2015                     # [win]
llibcxx:
  - 14.0.6                    # [linux]
  - 14.0.6                    # [osx]
  - 14.0.6                    # [osxarm64]
  - 14.0.6                    # [win]
channels:
  - Numerics88
  - conda-forge
  - defaults