c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2015                     # [win]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2015                     # [win]
llibcxx:
  - 14.0.6
cxx_compiler_version:
  - 15.0.7
clang_variant:
  - default
channels:
  - Numerics88
  - conda-forge
  - defaults