
package:
  name: n88util-test
  version: {{ GIT_RELEASE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0

requirements:
  build:
    - cmake >=3.30.3
    - boost >=1.56
    - ninja
    - gtest
    - libcxx <=14.0.6
    - rhash
    - {{ compiler('cxx') }}
  host:
    - libcxx <=14.0.6
    - rhash
  run:
    - boost >=1.56
    - libcxx <=14.0.6
    - python >=3.9

about:
  home: https://github.com/Numerics88/n88util
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Numerics88 utility classes and functions'
  description: |
    Typical random collection of C++ classes and functions that do all the
    little things we need all the time.
  dev_url: https://github.com/Numerics88/n88util