
package:
  name: n88util
  version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake >=3.1.0
    - boost >=1.56.0
    - ninja
    - gtest
  host:
    - boost >=1.56.0
  run:
    - boost >=1.56.0

about:
  home: https://github.com/Numerics88/n88util
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Numerics88 utility classes and functions'
  description: |
    Typical random collection of C++ classes and functions that do all the
    little things we need all the time.
  dev_url: https://github.com/Numerics88/n88util
