name: build-publish-anaconda

on:
    push:
      branches:
        - kean/ci
    workflow_dispatch:

jobs:
    build-and-publish:
        name: Conda deployment
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            # OS types: Windows x64, macOS 13 (last intel based runner), macOS latest (Apple silicon), and Ubuntu x64
            # Python versions: 3.9, 3.10, and 3.11
            # ------------------------------------------------------
            # os: ["windows-latest", "macos-13", "macos-latest", "ubuntu-latest"]
            # python-minor-version: [9,10,11,12]
            os: ["ubuntu-latest"]
            python-minor-version: [11]

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: kean/ci # UPDATE: Change to master branch when finished testing
            
          - name: Build and publish
            uses: openalea/action-build-publish-anaconda@v0.1.5
            with:
              conda: conda-recipe/n88util
              mamba: false
              python: ${{ matrix.python-minor-version }}
              numpy: '22'
              channels: friedchickean, Numerics88, conda-forge, defaults
              token: ${{ secrets.KEAN_CONDA_TOKEN }}
              publish: false
              label: main
