# This workflow builds and publishes the conda package to the Numerics88 channel
# using the openalea/action-build-publish-anaconda action.
name: Conda Build And Publish

on:

    push:
      branches:
        - kean/ci
    workflow_dispatch:

jobs:
    build-and-publish:
        name: Conda deployment
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            # OS types: Windows x64, macOS 13 (last intel based runner), macOS latest (Apple silicon), and Ubuntu x64
            # ------------------------------------------------------
            os: ["macos-latest", "macos-13"]
            python-minor-version: [9]

        steps:
          - name: Download MacOSX10.9 SDK
            if: matrix.os == 'macos-13'
            run: |
              curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz -o MacOSX10.9.sdk.tar.xz
              tar -xf MacOSX10.9.sdk.tar.xz
              sudo mv MacOSX10.9.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
          - name: Set CONDA_BUILD_SYSROOT
            if: matrix.os == 'macos-13'
            run: echo "CONDA_BUILD_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk" >> $GITHUB_ENV
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: kean/ci # UPDATE: Change to master branch when finished testing
              fetch-depth: 0 # Fetch all history for all branches and tags

          - name: Fetch all tags
            run: git fetch --tags
            shell: bash

          - name: Set GIT_RELEASE_TAG # Fetch and set the latest release tag
            run: |
              LATEST_TAG=$(git describe --abbrev=0 --tags --always)
              echo "GIT_RELEASE_TAG=$LATEST_TAG" >> $GITHUB_ENV
            shell: bash
            
          - name: Build and publish
            uses: openalea/action-build-publish-anaconda@v0.1.5
            with:
              conda: conda-recipe/n88util
              mamba: false
              python: ${{ matrix.python-minor-version }}
              numpy: '22'
              channels: Numerics88, defaults, friedchickean
              token: ${{ secrets.KEAN_CONDA_TOKEN }}
              publish: true
              label: main
