# build-and-upload-conda-packages.yaml
# Refer to https://github.com/uibcdf/action-build-and-upload-conda-packages
name: Build and upload platform-specific conda packages

on:
  push:
    branches:
      - kean/ci
  workflow_dispatch: # Allows manual execution of the workflow

jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: kean/ci # UPDATE: Change to master branch when finished testing

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: conda-recipe/n88util/environment.yml  # Path to conda environment file
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Set GIT_DESCRIBE_TAG # This is a custom step to set the GIT_DESCRIBE_TAG environment variable
        run: |
          echo "GIT_DESCRIBE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
        shell: bash 

      - name: Install Conda Build
        run: conda install -y conda-build

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          python-version: 3.9 # needed for conda-build
          meta_yaml_dir: conda-recipe/n88util
          user: skboyd # Anaconda username (or an Anaconda organization username Numerics88?)
          token: ${{ secrets.N88UTIL_NUMERICS88 }}
          upload: false # UPDATE: Change to true when finished testing

