# This workflow builds and publishes the conda package to the Numerics88 channel
# using the openalea/action-build-publish-anaconda action.
name: Conda Build And Publish

on:

    push:
      branches:
        - kean/ci
    workflow_dispatch:

jobs:
    build-and-publish:
        name: Conda deployment
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            # OS types: Windows x64, macOS 13 (last intel based runner), macOS latest (Apple silicon), and Ubuntu x64
            # ------------------------------------------------------
            os: ["macos-13", "macos-latest", "windows-latest", "ubuntu-latest"]
            python-minor-version: [9]

        steps:
          - name: Set CONDA_BUILD_SYSROOT (MacOS 13)
            if: matrix.os == 'macos-13'
            run: echo "CONDA_BUILD_SYSROOT=/Applications/Xcode_14.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" >> $GITHUB_ENV

          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: kean/ci # UPDATE: Change to master branch when finished testing
              fetch-depth: 0 # Fetch all history for all branches and tags

          - name: Add "conda deactivate" to the start of conda-recipe/n88util/build.sh
            if: matrix.os == 'macos-13'
            run: |
              sed -i '' '2i\
              conda deactivate' ./conda-recipe/n88util/build.sh
            shell: bash

          - name: Fetch all tags
            run: git fetch --tags
            shell: bash

          - name: Set GIT_RELEASE_TAG # Fetch and set the latest release tag
            run: |
              LATEST_TAG=$(git describe --abbrev=0 --tags --always)
              echo "GIT_RELEASE_TAG=$LATEST_TAG" >> $GITHUB_ENV
            shell: bash
            
          - name: Build and publish
            uses: openalea/action-build-publish-anaconda@v0.1.5
            with:
              conda: conda-recipe/n88util
              mamba: false
              python: ${{ matrix.python-minor-version }}
              numpy: '22'
              channels: Numerics88, defaults, friedchickean
              token: ${{ secrets.KEAN_CONDA_TOKEN }}
              publish: true
              label: main
