# build-and-upload-conda-packages.yaml
# Refer to https://github.com/uibcdf/action-build-and-upload-conda-packages
name: Build and upload platform-specific conda packages

on:
  push:
    branches:
      - kean/ci
  workflow_dispatch: # Allows manual execution of the workflow

jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: kean/ci # UPDATE: Change to master branch when finished testing

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: conda-recipe/n88util/environment.yml  # Path to conda environment file
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      # - name: Create Conda Environment
      #   run: conda create -y -n n88 python=3 conda-build

      # - name: Activate Conda Environment and Build
      #   run: |
      #     conda init
      #     conda activate n88
      #     conda build conda-recipe/n88util/

      # - name: Save Built Package as Artifact # For Debugging
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: n88util-Linux
      #     path: /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2
      #   if: always()

      - name: Install Conda Build
        run: conda install -y conda-build

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          python-version: 3.9
          python: 3.9 # uibcdf removed python version but conda build needs it
          meta_yaml_dir: conda-recipe/n88util
          user: skboyd # Anaconda username (or an Anaconda organization username Numerics88?)
          token: ${{ secrets.N88UTIL_NUMERICS88 }}
          upload: false # UPDATE: Change to true when finished testing

