# build-and-upload-conda-packages.yaml
# Refer to https://github.com/uibcdf/action-build-and-upload-conda-packages
name: Build and upload platform-specific conda packages

on:
  push:
    branches:
      - kean/ci
  workflow_dispatch: # Allows manual execution of the workflow

jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # run on Windows, macOS x64 intel based, macOS arm64 apple silicon, and Linux
        os: ["windows-latest", "macos-latest", "macos-11", "ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11"]
        

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: kean/ci # UPDATE: Change to master branch when finished testing
      
      - name: Verify OS type, architecture, and Python version
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Python version: ${{ matrix.python-version }}"
          echo "Architecture: $(uname -m)"
        shell: bash

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: conda-recipe/n88util/environment.yml  # Path to conda environment file
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Set GIT_DESCRIBE_TAG # This is a custom step to set the GIT_DESCRIBE_TAG environment variable
        run: |
          echo "GIT_DESCRIBE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
        shell: bash

      - name: Install Conda Build
        run: conda install -y conda-build

      - name: Setup MSVC Environment (Windows)
        if: runner.os == 'Windows'
        run: |
            for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do set VS_PATH=%%i
            call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
            set >> %GITHUB_ENV%
        shell: cmd

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          python-version: ${{ matrix.python-version }} # needed for conda-build
          meta_yaml_dir: conda-recipe/n88util
          user: skboyd # Anaconda username (or an Anaconda organization username Numerics88?)
          token: ${{ secrets.N88UTIL_NUMERICS88 }}
          upload: false # UPDATE: Change to true when finished testing

      - name: Find Conda build output path
        id: conda_output
        run: echo "PACKAGE_PATH=$(conda build conda-recipe/n88util --output)" >> $GITHUB_ENV
        shell: bash

      - name: Upload Conda artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda-artifact-${{ matrix.os }}-${{ matrix.python-version }}
          path: ${{ env.PACKAGE_PATH }}