# build-and-upload-conda-packages.yaml
# Refer to https://github.com/uibcdf/action-build-and-upload-conda-packages
name: Build and upload platform-specific conda packages

on:
  push:
    branches:
      - kean/ci
  workflow_dispatch: # Allows manual execution of the workflow

jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest-x64, macos-latest-arm64, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
        include:
          - os: macos-latest-x64
            arch: x64
            conda_subdir: osx-64
          - os: macos-latest-arm64
            arch: arm64
            conda_subdir: osx-arm64
          - os: ubuntu-latest
            arch: x64
            conda_subdir: linux-64
          - os: windows-latest
            arch: x64
            conda_subdir: win-64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: kean/ci # UPDATE: Change to master branch when finished testing

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: conda-recipe/n88util/environment.yml  # Path to conda environment file
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Set GIT_DESCRIBE_TAG # This is a custom step to set the GIT_DESCRIBE_TAG environment variable
        run: |
          echo "GIT_DESCRIBE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
        shell: bash

      - name: Install Conda Build
        run: conda install -y conda-build

      - name: Setup MSVC Environment (Windows)
        if: runner.os == 'Windows'
        run: |
            for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do set VS_PATH=%%i
            call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
            set >> %GITHUB_ENV%
        shell: cmd

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          python-version: ${{ matrix.python-version }} # needed for conda-build
          meta_yaml_dir: conda-recipe/n88util
          user: skboyd # Anaconda username (or an Anaconda organization username Numerics88?)
          token: ${{ secrets.N88UTIL_NUMERICS88 }}
          upload: false # UPDATE: Change to true when finished testing
      
      - name: Print Conda build output path # more debugging info. 
        run: conda build conda-recipe/n88util --output