# This workflow builds and publishes the conda package to the Numerics88 channel
# using the openalea/action-build-publish-anaconda action.
name: Conda Build And Publish

on:

    push:
      branches:
        - kean/ci
    workflow_dispatch:

jobs:
    build-and-publish:
        name: Conda deployment
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            # OS types: Windows x64, macOS 13 (last intel based runner), macOS latest (Apple silicon), and Ubuntu x64
            # ------------------------------------------------------
            os: ["macos-latest", "macos-13", "ubuntu-latest", "windows-latest"]
            python-minor-version: [9]

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: kean/ci # UPDATE: Change to master branch when finished testing

          - name: Set GIT_RELEASE_TAG # Fetch and set the latest release tag
            run: |
              git fetch --tags
              LATEST_TAG=$(git describe --abbrev=0 --tags)
              echo "GIT_RELEASE_TAG=$LATEST_TAG" >> $GITHUB_ENV
            # run: |
            #     echo "GIT_RELEASE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
            shell: bash
            
          - name: Build and publish
            uses: openalea/action-build-publish-anaconda@v0.1.5
            with:
              conda: conda-recipe/n88util
              mamba: false
              python: ${{ matrix.python-minor-version }}
              numpy: '22'
              channels: Numerics88, defaults, friedchickean
              token: ${{ secrets.KEAN_CONDA_TOKEN }}
              publish: true
              label: main
