name: Test Windows C++ Compiler

on:
    push:
      branches:
        - kean/ci
    workflow_dispatch: # Allows manual execution of the workflow

jobs:
  test_cxx_compiler:
    name: Test C++ Compiler on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: conda-recipe/n88util/environment.yml  # Path to conda environment file
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Print MSVC path
        if: runner.os == 'Windows'
        run: echo "VSINSTALLDIR=$VSINSTALLDIR" >> $GITHUB_ENV
        shell: bash
    
      - name: Install Build Tools
        run: conda install -y cmake ninja m2w64-toolchain vs2017_win-64

      - name: Set up MSVC environment
        if: runner.os == 'Windows'
        run: |
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvars64.bat"
        shell: cmd

      - name: Verify C++ Compiler
        run: |
          cl.exe /?
        shell: cmd

      - name: Create Build Directory
        run: mkdir build

      - name: Run CMake Configuration
        run: |
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe
        shell: cmd

      - name: Print Environment Variables
        run: set
        shell: cmd