name: Test Windows C++ Compiler

on:
    push:
      branches:
        - kean/ci
    workflow_dispatch: # Allows manual execution of the workflow

jobs:
  test_cxx_compiler:
    name: Test C++ Compiler on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: conda-recipe/n88util/environment.yml  # Path to conda environment file
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Look for MSVC path
        run: |
          dir "C:\Program Files (x86)\Microsoft Visual Studio"
        shell: cmd

      - name: Print Environment Variables
        run: set
        shell: cmd